version: "3"

services:
  backend:
    build: .
    command: >
      sh -c "aerich upgrade
             uvicorn main:app --reload --host 0.0.0.0 --port 5001"
    volumes:
      - .:/code
    ports:
      - "5001:5001"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres-volu:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bewise_dbname
      - POSTGRES_USER=bewise_usr
      - POSTGRES_PASSWORD=bewise_pswd
volumes:
  postgres-volu:
